server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pickdler
    username: postgres
    password: 123456
    pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: false